INSERT INTO PUBLIC.DOJO(ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME, CITY, NUMBER, STATE, STREET, CEP) VALUES 
(1, NULL, NULL, NULL, NULL, 'Kitahira Dojo', 'Joinville', 71, 'SC', STRINGDECODE('Rua Xanxerê'), NULL),
(2, NULL, NULL, NULL, NULL, 'Ultimate Fight & Fitness Club', 'Joinville', 836, 'SC', 'Rua Santa Catarina', NULL), 
(3, NULL, NULL, NULL, NULL, 'Miami No Tani Dojo', STRINGDECODE('Jaraguá do Sul'), 835, 'SC', 'Rua Walter Marquard', NULL);

INSERT INTO PUBLIC.CLASS_TYPE(ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NAME) VALUES 
(1, NULL, NULL, NULL, NULL, 'Aikido'),
(2, NULL, NULL, NULL, NULL, 'Aikido Graduados'),
(3, NULL, NULL, NULL, NULL, 'Quedas'),
(4, NULL, NULL, NULL, NULL, 'Slow Aiki'),
(5, NULL, NULL, NULL, NULL, 'Yudansha');

INSERT INTO PUBLIC.BELT(ID, BELT_TIME, COLOR, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NEXT_BELT_ID, COLOR_CODE, CHILD) VALUES 
(1, NULL, 'YonDan', NULL, NULL, NULL, NULL, NULL, '#000', FALSE), 
(2, NULL, 'SanDan', NULL, NULL, NULL, NULL, 1, '#000', FALSE), 
(3, NULL, 'NiDan', NULL, NULL, NULL, NULL, 2, '#000', FALSE), 
(4, NULL, 'ShoDan', NULL, NULL, NULL, NULL, 3, '#000', FALSE), 
(5, NULL, 'Marrom', NULL, NULL, NULL, NULL, 4, '#784212', FALSE), 
(6, NULL, 'Azul', NULL, NULL, NULL, NULL, 5, '#2874A6', FALSE), 
(7, NULL, 'Verde', NULL, NULL, NULL, NULL, 6, '#229954', FALSE), 
(8, NULL, 'Roxa', NULL, NULL, NULL, NULL, 7, '#6C3483', FALSE), 
(9, NULL, 'Amarela', NULL, NULL, NULL, NULL, 8, '#F1C40F', FALSE), 
(10, NULL, 'Branca', NULL, NULL, NULL, NULL, 9, '#fdfefe', FALSE);

INSERT INTO PUBLIC.BELT(ID, BELT_TIME, CHILD, COLOR, COLOR_CODE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, NEXT_BELT_ID) VALUES
(11, NULL, TRUE, 'Vermelha ponta Amarela', '#ff0000', NULL, NULL, NULL, NULL, 9),
(12, NULL, TRUE, 'Vermelha', '#ff0000', NULL, NULL, NULL, NULL, 11),
(13, NULL, TRUE, 'Cinza ponta Vermelha', '#808080', NULL, NULL, NULL, NULL, 12),
(14, NULL, TRUE, 'Cinza', '#808080', NULL, NULL, NULL, NULL, 13),
(15, NULL, TRUE, 'Laranja ponta Cinza', '#ff8000', NULL, NULL, NULL, NULL, 14),
(17, NULL, TRUE, 'Laranja ponta Branca', '#ff8000', NULL, NULL, NULL, NULL, 15),
(18, NULL, TRUE, 'Laranja', '#ff8000', NULL, NULL, NULL, NULL, 17),
(19, NULL, TRUE, 'Branca 2 pontas Laranja', '#ffffff', NULL, NULL, NULL, NULL, 18),
(20, NULL, TRUE, 'Branca ponta Laranja', '#ffffff', NULL, NULL, NULL, NULL, 19),
(21, NULL, TRUE, 'Branca', '#ffffff', NULL, NULL, NULL, NULL, 20);

